### ISSUE TITLE
User assert to add test cases to algorithms

### ISSUE THREAD

**Issue by Motor-taxi-master-rider** [naixy28/leetcode-kowai#1]
I find it a bit difficult to understand the functionality of a algorithm since we've solved more _leetcode_ problems. Is it possible to use `assert` to add some test cases below these algorithms. I think it will be more easy for reader to read and learn.

**Comment by naixy28** [comment]
Good idea.
For now this repo is more like a playground to record what I have coded.  But i believe it is essential to add assertions for better understanding.
Thanks, Charlie. I'll look into it ;)

**Comment by Motor-taxi-master-rider** [comment]
I'm look forward to this. Try my best to learn some advanced javascript.
